### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by o98k-ok** [nv-tlabs/editGAN_release#1]
When I run `run_app.py`, I got a exception: 
<img width="1848" alt="image" src="https://user-images.githubusercontent.com/63107263/154911632-14b3f5b1-8606-453b-85d0-413cb8f08c3c.png">
I am not run `run_app.py` on Tesla v100. I only have 16G GPU memory, how can I make it run successfully.

In addition I have adjust `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:21`, it still cannot finish.

**Comment by arieling** [comment]
Hi, Thank you for your interest. In this work, we only tested on V100 GPUs with **32GB** memory. 

If you want to use 16G GPU memory V100, there are also multiple tricks to reduce memory usage. For example, you can consider reducing stylegan model size to 256* 256 or you can use fewer stylegan features and reduce DatasetGAN input feature size as indicated in https://github.com/nv-tlabs/editGAN_release/blob/release_final/experiments/datasetgan_car.json#L6. or reduce ensemble model number as indicated https://github.com/nv-tlabs/editGAN_release/blob/release_final/experiments/datasetgan_car.json#L15. 
However, it's out of the scope of our discussion of the current EditGAN project.
