### ISSUE TITLE
How to edit custom image of car

### ISSUE THREAD

**Issue by chobao** [nv-tlabs/editGAN_release#12]
Hi, I run the app and find the "upload image" button. It seems to support editing custom images. However, when I upload a custom image of the car, the semantic image on the left does not change simultaneously so that I can not edit it. Can you offer me a tutorial on how to edit custom images?

**Comment by arieling** [comment]
You need to draw a box on your uploaded image.

**Comment by chobao** [comment]
Thanks! I successfully edit custom images with your excellent work. But there is still a problem that the image reconstructed by editGAN(after `run_embedding`) is not exactly the same as the image uploaded. It's probably because there is no proper code in learned latent space to reconstruct the uploaded image perfectly. Do you have an idea about it?
![image](https://user-images.githubusercontent.com/53040496/166630903-48b03ca0-2f3d-4bea-8ee2-fbecd50a9539.png)

**Comment by cssddnnc9527** [comment]
@1612190130 hi, i'm really curious about how you reconstructed car image through editGan. Do U generate it by mask image? Cause i'm failed to generate new image by modify the mask image. Can you run the UI tool of editGan correctly?

**Comment by ucasligang** [comment]
[You can consider this simple script for inference.](https://github.com/nv-tlabs/editGAN_release/issues/13#issuecomment-1150902676)
