### ISSUE TITLE
fail to run the app CUDA out of memory

### ISSUE THREAD

**Issue by talhaortas** [nv-tlabs/editGAN_release#23]
Hi! I've got this trouble when I tried to run the app.
`    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 5.01 GiB already allocated; 0 bytes free; 5.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memor
y try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
127.0.0.1 - - [18/Nov/2022 14:52:07] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [18/Nov/2022 14:52:07] "GET /favicon.ico HTTP/1.1" 404 -
`

i'm new to this stuff
how can i solve this problem?

**Comment by arieling** [comment]
Hi.  Our experiments are based on NVIDIA Tesla V100 GPUs with 32GB memory.

**Comment by talhaortas** [comment]
What should I do to arrange it according to 6gb gpu ram?
can't i limit ram usage?
i am using nvidia 3060 graphics card
Or can you give a hint to guide the way?
