### ISSUE TITLE
Hello, can you realease the pretrained FFHQ face model of editgan?Thanks

### ISSUE THREAD

**Issue by zeta7337** [nv-tlabs/editGAN_release#3]
hello ,thanks for your great contribution,can you realease the pretrained FFHQ face model of editgan?

**Comment by arieling** [comment]
Hi,

No.  FFHQ face model could not be released due to our internal policy restriction.

However, All data and code required to reproduce face results are released.

Thanks.

**Comment by zeta7337** [comment]
> Hi,
> 
> No. FFHQ face model could not be released due to our internal policy restriction.
> 
> However, All data and code required to reproduce face results are released.
> 
> Thanks.

thank you
