### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './static/results/current_editing_latent_cache.pickle'

### ISSUE THREAD

**Issue by su161021** [nv-tlabs/editGAN_release#7]
Excuse me, where can I download this file？

FileNotFoundError: [Errno 2] No such file or directory: './static/results/current_editing_latent_cache.pickle'

**Comment by silaopi** [comment]
> Excuse me, where can I download this file？
> 
> FileNotFoundError: [Errno 2] No such file or directory: './static/results/current_editing_latent_cache.pickle'

Hi, how did you solve this problem?
